# Generated by Django 4.1.5 on 2023-01-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(max_length=30),
        ),
    ]
