# Generated by Django 4.1.5 on 2023-01-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Débito", "Debito"),
                            ("Boleto", "Boleto"),
                            ("Financiamento", "Financiamento"),
                            ("Crédito", "Credito"),
                            ("Recebimento Empréstimo", "Emprestimo"),
                            ("Vendas", "Vendas"),
                            ("Recebimento TED", "Ted"),
                            ("Recebimento DOC", "Doc"),
                            ("Aluguel", "Aluguel"),
                        ],
                        default="Débito",
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField(max_length=10)),
                ("cpf", models.IntegerField(max_length=11)),
                ("card", models.CharField(max_length=12)),
                ("hour", models.TimeField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="stores.store",
                    ),
                ),
            ],
        ),
    ]
