# Generated by Django 4.1.5 on 2023-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_alter_store_balance_alter_store_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
