# Generated by Django 4.1.5 on 2023-01-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_alter_store_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="balance",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
