# Generated by Django 4.1.5 on 2023-01-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_store_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=19),
        ),
    ]
